name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  # Job 1: Checkout Code and Scan with SonarScanner
  sonar-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=springmongo-frontend \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

  docker-build-push:
    needs: sonar-scan
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t 7987937230/springmongo-frontend:${{ github.sha }} .

      # Step 4: Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        run: |
          trivy image --scanners vuln 7987937230/springmongo-frontend:${{ github.sha }}
          
      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push 7987937230/springmongo-frontend:${{ github.sha }}

  update-helm-repo:
    needs:  docker-build-push
    runs-on: self-hosted
    
    steps:
      - name: Checkout Helm project repository
        uses: actions/checkout@v3
        with:
          repository: kunal-drmarten/springmongo-helmchart # Replace with the actual repo name
          token: ${{ secrets.GIT_TOKEN }}  # GitHub token to access the second repo
          path: springmongo-helmchart  # Directory where the second repo will be checked out

      # Step 3: Modify the file in the second repository
      - name: Modify file in second repo
        run: |
          sed -i '' '/frontend:/,/tag:/s/tag: .*/tag: ${{ env.GITHUB_SHA }}/' springmongo-helmchart/springmongo-app/values.yaml


      # Step 4: Commit and push the changes to the second repository
      - name: Commit changes to second repository
        run: |
          cd springmongo-helmchart
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update file.txt with new changes"
          git push origin main  # Or the appropriate branch name
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} 
