name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Checkout Code and Scan with SonarScanner
  sonar-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=springmongo-frontend \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

  docker-build-push:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t 7987937230/springmongo-frontend:3 .

      # Step 4: Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        run: |
          trivy image --exit-code 1 --no-progress --scanners vuln 7987937230/springmongo-frontend:3
          
      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push 7987937230/springmongo-frontend:3

